# Generated by Django 5.0.2 on 2024-03-19 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rights', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserRightsMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rights_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rightuser', to='users.userrights')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userright', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
