# Generated by Django 5.0.2 on 2024-03-19 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_rights_userrights_right_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userrights',
            old_name='right',
            new_name='name',
        ),
    ]
