# Generated by Django 5.0.2 on 2024-03-19 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_right_userrightsmapping_rights'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userrightsmapping',
            old_name='rights',
            new_name='rights_name',
        ),
    ]
