# Generated by Django 4.2.4 on 2024-02-26 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("orgss", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Assessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "access",
                    models.CharField(
                        choices=[
                            ("pre", "PRE CHOICE"),
                            ("mid", "MID CHOICE"),
                            ("post", "POST CHOICE"),
                        ],
                        default=None,
                        max_length=30,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=500)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("hard", "Hard"),
                            ("difficult", "Difficult"),
                        ],
                        default=None,
                        max_length=30,
                    ),
                ),
                ("timer", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Option",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("option", models.CharField(max_length=500)),
                ("is_correct", models.BooleanField(default=False)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="assessment.question",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AssessmentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("passing_criteria", models.IntegerField(default=60)),
                ("positive_marks", models.IntegerField(blank=True, null=True)),
                ("negative_marks", models.IntegerField(blank=True, null=True)),
                ("time", models.IntegerField(blank=True, null=True)),
                (
                    "trigger_point",
                    models.CharField(
                        choices=[("days", "DAYS"), ("perentage", "PERCENTAGE")],
                        default=None,
                        max_length=30,
                    ),
                ),
                ("refresher_days", models.IntegerField(blank=True, null=True)),
                (
                    "suborg",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="orgss.suborg"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AssessmentResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phase",
                    models.CharField(
                        choices=[
                            ("pre", "PRE CHOICE"),
                            ("mid", "MID CHOICE"),
                            ("post", "POST CHOICE"),
                        ],
                        default=None,
                        max_length=30,
                    ),
                ),
                ("result", models.IntegerField()),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="assessment.assessment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="assessment",
            name="assessment_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="assessment.assessmenttype",
            ),
        ),
        migrations.AddField(
            model_name="assessment",
            name="questions",
            field=models.ManyToManyField(to="assessment.question"),
        ),
    ]
