# Generated by Django 5.0.2 on 2024-03-08 16:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assessments", "0001_initial"),
        ("orgss", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Assessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "access",
                    models.CharField(
                        choices=[
                            ("pre", "PRE CHOICE"),
                            ("mid", "MID CHOICE"),
                            ("post", "POST CHOICE"),
                        ],
                        default=None,
                        max_length=30,
                    ),
                ),
                ("questions", models.ManyToManyField(to="assessments.question")),
            ],
        ),
        migrations.CreateModel(
            name="AssessmentResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phase",
                    models.CharField(
                        choices=[
                            ("pre", "PRE CHOICE"),
                            ("mid", "MID CHOICE"),
                            ("post", "POST CHOICE"),
                        ],
                        default=None,
                        max_length=30,
                    ),
                ),
                ("result", models.IntegerField()),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="assessments.assessment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AssessmentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("passing_criteria", models.IntegerField(default=60)),
                ("positive_marks", models.IntegerField(blank=True, null=True)),
                ("negative_marks", models.IntegerField(blank=True, null=True)),
                ("time", models.IntegerField(blank=True, null=True)),
                (
                    "trigger_point",
                    models.CharField(
                        choices=[("days", "DAYS"), ("perentage", "PERCENTAGE")],
                        default=None,
                        max_length=30,
                    ),
                ),
                ("refresher_days", models.IntegerField(blank=True, null=True)),
                (
                    "suborg",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="orgss.suborg"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="assessment",
            name="assessment_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="assessments.assessmenttype",
            ),
        ),
    ]
