# Generated by Django 5.0.2 on 2024-03-23 13:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assessments", "0002_assessment_assessmentresult_assessmenttype_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessmentresult",
            name="created_at",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
