# Generated by Django 5.0.2 on 2024-03-25 15:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assessments", "0003_assessmentresult_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessment",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="assessment",
            name="is_live",
            field=models.BooleanField(default=False),
        ),
    ]
