# Generated by Django 4.2.4 on 2024-02-26 16:30

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("words", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Scenarios",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_name", models.CharField(max_length=300)),
                ("item_emotions", models.TextField(blank=True, null=True)),
                ("own_scenarios", models.TextField(blank=True, null=True)),
                (
                    "negative_words",
                    models.ManyToManyField(blank=True, to="words.negativewords"),
                ),
                (
                    "power_words",
                    models.ManyToManyField(blank=True, to="words.powerwords"),
                ),
            ],
            options={
                "verbose_name_plural": "Scenarios",
            },
        ),
    ]
