# Generated by Django 4.2.4 on 2023-12-13 17:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("scenarios", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="scenarios",
            old_name="weak_words",
            new_name="negative_words",
        ),
    ]
