# Generated by Django 4.2.4 on 2023-12-22 15:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scenarios", "0002_rename_weak_words_scenarios_negative_words"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scenarios",
            name="item_emotions",
            field=models.TextField(blank=True, null=True),
        ),
    ]
