# Generated by Django 4.2.4 on 2023-08-31 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('industry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Org',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=250)),
                ('org_description', models.CharField(blank=True, max_length=500)),
                ('org_industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='industry', to='industry.industry')),
            ],
        ),
    ]
