# Generated by Django 4.2.4 on 2023-08-31 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0001_initial'),
        ('organisation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Org_Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_role_name', models.CharField(blank=True, max_length=250, null=True)),
                ('org_na', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='org1', to='organisation.org')),
                ('org_role', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='roles1', to='role.roles')),
                ('subrole_org', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='org', to='role.sub_role')),
            ],
        ),
    ]
