# Generated by Django 4.2.4 on 2023-09-04 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competency', '0001_initial'),
        ('organisation', '0002_org_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='org_roles',
            name='competency_weight',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='org_roles',
            name='role_competency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rolecompetency', to='competency.competency'),
        ),
        migrations.AddField(
            model_name='org_roles',
            name='role_subcompetency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rolesubcompetency', to='competency.sub_competency'),
        ),
        migrations.AddField(
            model_name='org_roles',
            name='subcompetency_weight',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='Role_Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_scenario_name', models.CharField(blank=True, max_length=250, null=True)),
                ('role_scenario', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rolescenario', to='organisation.org_roles')),
            ],
        ),
    ]
