# Generated by Django 4.2.4 on 2023-09-04 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sean', '0002_alter_item_thumbnail'),
        ('organisation', '0003_org_roles_competency_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='role_scenario',
            name='rolescenario_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rolescenario_item', to='sean.item'),
        ),
    ]
