# Generated by Django 4.2.4 on 2023-09-05 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0004_role_scenario_rolescenario_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Role_Scenario',
        ),
    ]
