# Generated by Django 4.2.4 on 2023-09-26 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competency', '0003_alter_competency_sub_competency'),
        ('organisation', '0005_delete_role_scenario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='org_roles',
            name='subcompetency_weight',
        ),
        migrations.AddField(
            model_name='org_roles',
            name='role_subcompetencys',
            field=models.ManyToManyField(blank=True, to='competency.sub_competency'),
        ),
    ]
