# Generated by Django 4.2.4 on 2023-09-23 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competency', '0003_alter_competency_sub_competency'),
        ('organisation', '0005_delete_role_scenario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='org_roles',
            name='competency_weight',
        ),
        migrations.RemoveField(
            model_name='org_roles',
            name='role_competency',
        ),
        migrations.RemoveField(
            model_name='org_roles',
            name='role_subcompetency',
        ),
        migrations.RemoveField(
            model_name='org_roles',
            name='subcompetency_weight',
        ),
        migrations.CreateModel(
            name='Weightage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(default=1)),
                ('org_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisation.org_roles')),
                ('subcompetency', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='competency.sub_competency')),
            ],
        ),
    ]
