# Generated by Django 4.2.4 on 2023-09-26 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0006_remove_org_roles_subcompetency_weight_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='org_roles',
            name='role_subcompetency',
        ),
    ]
