# Generated by Django 4.2.4 on 2023-09-23 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0006_remove_org_roles_competency_weight_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='org',
            old_name='org_industry',
            new_name='industry',
        ),
        migrations.RenameField(
            model_name='org',
            old_name='org_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='org_roles',
            old_name='org_na',
            new_name='org',
        ),
        migrations.RenameField(
            model_name='org_roles',
            old_name='subrole_org',
            new_name='org_subrole',
        ),
        migrations.RemoveField(
            model_name='org',
            name='org_description',
        ),
        migrations.AddField(
            model_name='org',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
