# Generated by Django 4.2.4 on 2023-09-24 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0007_rename_org_industry_org_industry_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='org_roles',
            old_name='org_role',
            new_name='role',
        ),
        migrations.RenameField(
            model_name='org_roles',
            old_name='org_subrole',
            new_name='subrole',
        ),
    ]
