# Generated by Django 4.2.4 on 2023-09-04 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=256)),
                ('item_description', models.CharField(max_length=300)),
                ('item_answer', models.TextField(default='Your answer', max_length=700)),
                ('item_answercount', models.IntegerField(default=1)),
                ('category', models.CharField(blank=True, default='English', max_length=256)),
                ('thumbnail', models.ImageField(default='c.png', upload_to='media')),
                ('tip', models.CharField(default='Tip', max_length=300)),
                ('appearance', models.CharField(default='appear', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('suggestion_text', models.TextField()),
            ],
        ),
    ]
