# Generated by Django 4.2.4 on 2023-09-27 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sean', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='negativewords',
            name='sub_competency',
        ),
        migrations.RemoveField(
            model_name='negativewords',
            name='word',
        ),
        migrations.RemoveField(
            model_name='powerwords',
            name='sub_competency',
        ),
        migrations.RemoveField(
            model_name='powerwords',
            name='word',
        ),
        migrations.RemoveField(
            model_name='item',
            name='competency_emotion_word',
        ),
        migrations.RemoveField(
            model_name='item',
            name='competency_power_words',
        ),
        migrations.RemoveField(
            model_name='item',
            name='competency_weak_words',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sub_competency',
        ),
        migrations.DeleteModel(
            name='EmotionWords',
        ),
        migrations.DeleteModel(
            name='NegativeWords',
        ),
        migrations.DeleteModel(
            name='PowerWords',
        ),
    ]
