# Generated by Django 4.2.6 on 2023-10-19 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sean', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='role',
        ),
        migrations.AddField(
            model_name='item',
            name='scenario_type',
            field=models.CharField(choices=[('Sales', 'Sales'), ('Customer Service', 'Customer Service'), ('Interview', 'Interview')], default='Sales', max_length=16),
        ),
        migrations.AlterField(
            model_name='item',
            name='user_powerwords',
            field=models.CharField(default='up', max_length=300),
        ),
        migrations.AlterField(
            model_name='item',
            name='user_weakwords',
            field=models.CharField(default='unp', max_length=300),
        ),
    ]
