# Generated by Django 5.0.2 on 2024-03-10 08:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sean", "0002_alter_item_expert_alter_item_negative_traits_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="negative_traits",
        ),
        migrations.RemoveField(
            model_name="item",
            name="positive_traits",
        ),
        migrations.RemoveField(
            model_name="item",
            name="user_powerwords",
        ),
        migrations.RemoveField(
            model_name="item",
            name="user_weakwords",
        ),
        migrations.AlterField(
            model_name="item",
            name="item_answer",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="item_answercount",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="item",
            name="item_emotion",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="item_gender",
            field=models.CharField(
                choices=[("female", "Female"), ("male", "Male"), ("all", "All")],
                default="all",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="item_type",
            field=models.CharField(
                choices=[("simulation", "Simulation"), ("email", "Email")],
                default="simulation",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="scenario_type",
            field=models.CharField(
                choices=[
                    ("sales", "Sales"),
                    ("customer_service", "Customer Service"),
                    ("interview", "Interview"),
                ],
                default="sales",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="thumbnail",
            field=models.FileField(
                blank=True, null=True, upload_to="media/item/thumbnail"
            ),
        ),
    ]
