# Generated by Django 4.2.4 on 2023-09-04 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sean', '0002_alter_item_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='thumbnail',
            field=models.ImageField(default='c.png', upload_to='media'),
        ),
    ]
