# Generated by Django 4.2.4 on 2023-09-28 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgss', '0001_initial'),
        ('sean', '0003_item_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orgss.org_roles'),
        ),
    ]
