# Generated by Django 4.2.4 on 2023-09-04 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sean', '0003_alter_item_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_emotion',
            field=models.TextField(default='emotions'),
        ),
    ]
