# Generated by Django 4.2.4 on 2023-09-04 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sean', '0004_item_item_emotion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(blank=True, default='Personal', max_length=256),
        ),
    ]
