# Generated by Django 4.2.4 on 2023-10-30 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sean', '0004_alter_item_item_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='coming_across_as',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
