# Generated by Django 4.2.4 on 2023-11-20 18:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sean", "0005_alter_item_coming_across_as"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="user_powerwords",
            field=models.CharField(default="up", max_length=2000),
        ),
        migrations.AlterField(
            model_name="item",
            name="user_weakwords",
            field=models.CharField(default="unp", max_length=2000),
        ),
    ]
