# Generated by Django 4.2.4 on 2023-10-02 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sean', '0005_remove_item_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='user_powerwords',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='item',
            name='user_weakwords',
            field=models.CharField(default='', max_length=300),
        ),
    ]
