# Generated by Django 4.2.4 on 2023-09-04 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sean', '0005_alter_item_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_gender',
            field=models.CharField(default='Female', max_length=25),
        ),
    ]
