# Generated by Django 5.0.2 on 2024-04-11 06:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sean", "0005_item_is_approved_item_is_live"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="item_video",
            field=models.FileField(blank=True, null=True, upload_to="media/item/video"),
        ),
    ]
