# Generated by Django 4.2.4 on 2023-09-04 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sean', '0006_item_item_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_gender',
            field=models.CharField(choices=[('Female', 'Gender 1'), ('Male', 'Gender 2'), ('All', 'Gender 3')], default='Female', max_length=7),
        ),
    ]
