# Generated by Django 5.0.2 on 2024-04-11 13:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sean", "0006_item_item_video"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="item_background",
            field=models.FileField(
                blank=True, null=True, upload_to="media/item/background"
            ),
        ),
    ]
