# Generated by Django 4.2.4 on 2024-02-22 17:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sean", "0007_alter_item_item_answer_alter_item_user_powerwords_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="role",
        ),
    ]
