# Generated by Django 5.0.2 on 2024-04-16 02:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sean", "0007_item_item_background"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="expert",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="item_background",
            field=models.URLField(blank=True, null=True),
        ),
    ]
