# Generated by Django 4.2.4 on 2023-09-05 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0005_delete_role_scenario'),
        ('sean', '0008_alter_item_item_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='organisation.org_roles'),
        ),
    ]
