# Generated by Django 5.0.2 on 2024-04-16 03:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sean", "0008_alter_item_expert_alter_item_item_background"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="item_background",
            field=models.FileField(
                blank=True, null=True, upload_to="media/item/item_background"
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="item_video",
            field=models.URLField(blank=True, null=True),
        ),
    ]
