# Generated by Django 4.2.4 on 2023-09-05 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sean', '0009_item_item_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='suggestions',
            field=models.CharField(default='sugestions', max_length=250),
        ),
    ]
