# Generated by Django 4.2.4 on 2023-09-08 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sean', '0011_rename_item_role_item_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='appearance',
            new_name='negative_words',
        ),
    ]
