# Generated by Django 4.2.4 on 2023-09-08 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competency', '0001_initial'),
        ('sean', '0012_rename_appearance_item_negative_words'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='competency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='competency.competency'),
        ),
        migrations.AddField(
            model_name='item',
            name='sub_competency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='competency.sub_competency'),
        ),
    ]
