# Generated by Django 4.2.4 on 2023-09-11 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sean', '0014_item_improvement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='suggestions',
            new_name='coming_across_as',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='tip',
            new_name='power_words',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='negative_words',
            new_name='weak_words',
        ),
        migrations.RemoveField(
            model_name='item',
            name='improvement',
        ),
    ]
