# Generated by Django 4.2.4 on 2023-09-12 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competency', '0001_initial'),
        ('sean', '0015_rename_suggestions_item_coming_across_as_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PowerWords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power_word_name', models.CharField(max_length=250)),
                ('competency', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='competency.competency')),
                ('sub_competency', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='competency.sub_competency')),
            ],
        ),
        migrations.CreateModel(
            name='NegativeWords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('negative_word_name', models.CharField(max_length=250)),
                ('competency', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='competency.competency')),
                ('sub_competency', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='competency.sub_competency')),
            ],
        ),
        migrations.CreateModel(
            name='EmotionWords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emotion_word_name', models.CharField(max_length=250)),
                ('competency', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='competency.competency')),
                ('sub_competency', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='competency.sub_competency')),
            ],
        ),
    ]
