# Generated by Django 4.2.4 on 2023-09-12 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sean', '0016_powerwords_negativewords_emotionwords'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='power_words',
        ),
        migrations.RemoveField(
            model_name='item',
            name='weak_words',
        ),
        migrations.AddField(
            model_name='item',
            name='competency_emotion_word',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sean.emotionwords'),
        ),
        migrations.AddField(
            model_name='item',
            name='competency_power_word',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sean.powerwords'),
        ),
        migrations.AddField(
            model_name='item',
            name='competency_weak_word',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sean.negativewords'),
        ),
    ]
