# Generated by Django 4.2.4 on 2023-09-12 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0005_delete_role_scenario'),
        ('sean', '0017_remove_item_power_words_remove_item_weak_words_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emotionwords',
            name='org_role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='organisation.org_roles'),
        ),
        migrations.AddField(
            model_name='negativewords',
            name='org_role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='organisation.org_roles'),
        ),
        migrations.AddField(
            model_name='powerwords',
            name='org_role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='organisation.org_roles'),
        ),
    ]
