# Generated by Django 4.2.4 on 2023-09-13 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sean', '0018_emotionwords_org_role_negativewords_org_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
