# Generated by Django 4.2.4 on 2023-09-13 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sean', '0021_alter_item_negative_traits_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='negative_traits',
            field=models.CharField(blank=True, default=' ', max_length=300),
        ),
        migrations.AlterField(
            model_name='item',
            name='positive_traits',
            field=models.CharField(blank=True, default=' ', max_length=300),
        ),
        migrations.AlterField(
            model_name='item',
            name='user_powerwords',
            field=models.CharField(default='up', max_length=300),
        ),
        migrations.AlterField(
            model_name='item',
            name='user_weakwords',
            field=models.CharField(default='unp', max_length=300),
        ),
    ]
