# Generated by Django 4.2.4 on 2023-09-14 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sean', '0023_negativewords_weight_powerwords_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('All', 'All')], default='All', max_length=7),
        ),
    ]
