# Generated by Django 4.2.4 on 2023-09-15 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0001_initial'),
        ('sean', '0024_alter_item_item_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='negativewords',
            name='word',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='words.words'),
        ),
        migrations.AddField(
            model_name='powerwords',
            name='word',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='words.words'),
        ),
    ]
