# Generated by Django 4.2.4 on 2023-09-16 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0001_initial'),
        ('sean', '0025_negativewords_word_powerwords_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='emotionwords',
            name='word',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='words.words'),
        ),
    ]
