# Generated by Django 4.2.4 on 2023-09-19 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sean', '0027_item_expert_negativewords_sentence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
