# Generated by Django 4.2.4 on 2023-09-19 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sean', '0028_alter_item_item_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='competency_power_word',
        ),
        migrations.AddField(
            model_name='item',
            name='competency_power_words',
            field=models.ManyToManyField(to='sean.powerwords'),
        ),
    ]
