# Generated by Django 4.2.4 on 2023-09-19 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sean', '0029_remove_item_competency_power_word_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='competency_weak_word',
        ),
        migrations.AddField(
            model_name='item',
            name='competency_weak_words',
            field=models.ManyToManyField(to='sean.negativewords'),
        ),
    ]
