# Generated by Django 4.2.4 on 2023-09-19 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sean', '0030_remove_item_competency_weak_word_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='competency_power_words',
            field=models.ManyToManyField(limit_choices_to={'competency'}, to='sean.powerwords'),
        ),
    ]
