# Generated by Django 4.2.4 on 2023-09-19 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sean', '0031_alter_item_competency_power_words'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='competency_power_words',
            field=models.ManyToManyField(limit_choices_to={'competency': models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='competency.competency')}, to='sean.powerwords'),
        ),
    ]
