# Generated by Django 4.2.4 on 2023-09-19 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sean', '0032_alter_item_competency_power_words'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='competency_power_words',
            field=models.ManyToManyField(limit_choices_to={'competency': True}, to='sean.powerwords'),
        ),
    ]
