# Generated by Django 4.2.4 on 2023-09-19 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competency', '0001_initial'),
        ('sean', '0034_alter_item_competency_power_words'),
    ]

    operations = [
        migrations.RenameField(
            model_name='negativewords',
            old_name='competency',
            new_name='competencys',
        ),
        migrations.AlterField(
            model_name='item',
            name='competency',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='competency.competency'),
        ),
        migrations.AlterField(
            model_name='item',
            name='competency_weak_words',
            field=models.ManyToManyField(blank=True, related_name='competency', to='sean.negativewords'),
        ),
        migrations.AlterField(
            model_name='item',
            name='sub_competency',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='competency.sub_competency'),
        ),
    ]
