# Generated by Django 4.2.4 on 2023-09-19 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sean', '0037_rename_competency_item_competencys'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emotionwords',
            old_name='competency',
            new_name='competencys',
        ),
        migrations.RenameField(
            model_name='powerwords',
            old_name='competency',
            new_name='competencys',
        ),
    ]
