# Generated by Django 4.2.4 on 2023-09-19 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sean', '0038_rename_competency_emotionwords_competencys_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='competency_power_words',
            field=models.ManyToManyField(blank=True, limit_choices_to={'competencys': True}, to='sean.powerwords'),
        ),
        migrations.AlterField(
            model_name='item',
            name='competency_weak_words',
            field=models.ManyToManyField(blank=True, limit_choices_to={'competencys': True}, to='sean.negativewords'),
        ),
    ]
