# Generated by Django 4.2.4 on 2023-09-19 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sean', '0039_alter_item_competency_power_words_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='negativewords',
            name='negative_word_name',
            field=models.CharField(default='ww', max_length=250),
        ),
        migrations.AlterField(
            model_name='powerwords',
            name='power_word_name',
            field=models.CharField(default='pw', max_length=250),
        ),
    ]
