# Generated by Django 4.2.4 on 2023-09-20 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sean', '0040_alter_negativewords_negative_word_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Traits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
