# Generated by Django 4.2.4 on 2023-09-20 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0001_initial'),
        ('sean', '0042_traits_trait_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='powerwords',
            name='word',
        ),
        migrations.AddField(
            model_name='powerwords',
            name='trait_name',
            field=models.CharField(default='trait', max_length=250),
        ),
        migrations.AddField(
            model_name='powerwords',
            name='trwords_name',
            field=models.ManyToManyField(to='words.words'),
        ),
    ]
