# Generated by Django 4.2.4 on 2023-09-20 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0001_initial'),
        ('sean', '0043_remove_powerwords_word_powerwords_trait_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='powerwords',
            name='trait_name',
        ),
        migrations.RemoveField(
            model_name='powerwords',
            name='trwords_name',
        ),
        migrations.AddField(
            model_name='powerwords',
            name='word',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='words.words'),
        ),
    ]
