# Generated by Django 4.2.4 on 2023-09-20 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sean', '0047_remove_powerwords_word_powerwords_word'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='competency_power_words',
            field=models.ManyToManyField(blank=True, to='sean.powerwords'),
        ),
        migrations.AlterField(
            model_name='item',
            name='competency_weak_words',
            field=models.ManyToManyField(blank=True, to='sean.negativewords'),
        ),
    ]
