# Generated by Django 4.2.4 on 2023-09-22 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sean', '0049_collection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='negativewords',
            name='competencys',
        ),
        migrations.RemoveField(
            model_name='negativewords',
            name='org_role',
        ),
        migrations.RemoveField(
            model_name='powerwords',
            name='competencys',
        ),
        migrations.RemoveField(
            model_name='powerwords',
            name='org_role',
        ),
    ]
