# Generated by Django 4.2.4 on 2023-09-27 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgss', '0002_weightage_role_competency_and_more'),
        ('sean', '0050_remove_negativewords_competencys_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emotionwords',
            name='org_role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='orgss.org_roles'),
        ),
        migrations.AlterField(
            model_name='item',
            name='role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='orgss.org_roles'),
        ),
    ]
