# Generated by Django 4.2.4 on 2023-09-27 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sean', '0051_alter_emotionwords_org_role_alter_item_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emotionwords',
            name='org_role',
        ),
    ]
