# Generated by Django 4.2.4 on 2023-10-04 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sean', '0054_alter_item_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='scenario_type',
            field=models.CharField(choices=[('Sales', 'Sales'), ('Customer Service', 'Customer Service'), ('Interview', 'Interview')], default='Sales', max_length=16),
        ),
    ]
