# Generated by Django 4.2.4 on 2023-10-11 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sean', '0056_item1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Traits',
        ),
    ]
