# Generated by Django 4.2.4 on 2023-10-11 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sean', '0057_delete_traits'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Collection',
        ),
    ]
