# Generated by Django 4.2.4 on 2023-10-11 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competency', '0010_remove_competency_sub_competency'),
        ('sean', '0058_delete_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emotionwords',
            name='competencys',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='competency.competency1'),
        ),
        migrations.AlterField(
            model_name='item',
            name='competencys',
            field=models.ManyToManyField(blank=True, to='competency.competency1'),
        ),
        migrations.AlterField(
            model_name='item',
            name='sub_competency',
            field=models.ManyToManyField(blank=True, to='competency.sub_competency1'),
        ),
    ]
