# Generated by Django 4.2.4 on 2023-10-11 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competency', '0011_delete_competency'),
        ('sean', '0059_alter_emotionwords_competencys_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emotionwords',
            name='sub_competency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='competency.sub_competency1'),
        ),
        migrations.AlterField(
            model_name='negativewords',
            name='sub_competency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='competency.sub_competency1'),
        ),
        migrations.AlterField(
            model_name='powerwords',
            name='sub_competency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='competency.sub_competency1'),
        ),
    ]
