# Generated by Django 4.2.4 on 2023-10-12 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sean', '0060_alter_emotionwords_sub_competency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='competency_emotion_word',
        ),
        migrations.DeleteModel(
            name='EmotionWords',
        ),
    ]
