# Generated by Django 4.2.4 on 2023-10-12 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sean', '0061_remove_item_competency_emotion_word_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='sub_competency',
        ),
    ]
