# Generated by Django 4.2.4 on 2023-10-13 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sean', '0062_remove_item_sub_competency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='competency_power_words',
        ),
        migrations.RemoveField(
            model_name='item',
            name='competency_weak_words',
        ),
    ]
