# Generated by Django 4.2.4 on 2023-10-13 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sean', '0063_remove_item_competency_power_words_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='negativewords',
            name='sub_competency',
        ),
        migrations.RemoveField(
            model_name='negativewords',
            name='word',
        ),
        migrations.RemoveField(
            model_name='powerwords',
            name='sub_competency',
        ),
        migrations.RemoveField(
            model_name='powerwords',
            name='word',
        ),
        migrations.DeleteModel(
            name='Item1',
        ),
        migrations.DeleteModel(
            name='NegativeWords',
        ),
        migrations.DeleteModel(
            name='PowerWords',
        ),
    ]
