# Generated by Django 4.2.4 on 2023-10-19 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('role', '0001_initial'),
        ('competency', '__first__'),
        ('industry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Org',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='industry', to='industry.industry')),
            ],
        ),
        migrations.CreateModel(
            name='Org_Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_role_name', models.CharField(blank=True, max_length=250, null=True)),
                ('org', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='orgss.org')),
                ('role', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='role.role')),
                ('subrole', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='role.sub_role')),
            ],
        ),
        migrations.CreateModel(
            name='Weightage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weightage', models.IntegerField(default=1)),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competency', to='competency.competency')),
                ('org_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgss.org_roles')),
            ],
        ),
    ]
