# Generated by Django 4.2.4 on 2023-09-27 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('industry', '0001_initial'),
        ('role', '0001_initial'),
        ('competency', '0004_alter_competency_competency_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Org',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('industry1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='industry1', to='industry.industry')),
            ],
        ),
        migrations.CreateModel(
            name='Org_Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_role_name', models.CharField(blank=True, max_length=250, null=True)),
                ('org', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='org1', to='orgss.org')),
                ('role', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='roles12', to='role.roles')),
                ('subrole', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='org1', to='role.sub_role')),
            ],
        ),
        migrations.CreateModel(
            name='Weightage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(default=1)),
                ('org_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgss.org_roles')),
                ('subcompetency', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='competency.sub_competency')),
            ],
        ),
    ]
