# Generated by Django 5.0.2 on 2024-04-11 06:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orgss", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="org",
            name="logo",
            field=models.FileField(blank=True, null=True, upload_to="media/logo"),
        ),
    ]
