# Generated by Django 4.2.4 on 2023-09-27 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competency', '0004_alter_competency_competency_name_and_more'),
        ('orgss', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weightage',
            name='role_competency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rolecompetency1', to='competency.competency'),
        ),
        migrations.RemoveField(
            model_name='weightage',
            name='subcompetency',
        ),
        migrations.AddField(
            model_name='weightage',
            name='subcompetency',
            field=models.ManyToManyField(blank=True, to='competency.sub_competency'),
        ),
    ]
