# Generated by Django 4.2.6 on 2023-10-19 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('industry', '0001_initial'),
        ('competency', '0003_rename_name_competency_competency_name'),
        ('orgss', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='org',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='org_roles',
            name='role',
        ),
        migrations.RemoveField(
            model_name='org_roles',
            name='subrole',
        ),
        migrations.AddField(
            model_name='org',
            name='industry1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='industry1', to='industry.industry'),
        ),
        migrations.AlterField(
            model_name='org_roles',
            name='org',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='org1', to='orgss.org'),
        ),
        migrations.AlterField(
            model_name='weightage',
            name='competency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rolecompetency1', to='competency.competency'),
        ),
    ]
