# Generated by Django 4.2.4 on 2023-12-31 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("competency", "0003_rename_name_competency_competency_name"),
        ("industry", "0001_initial"),
        ("orgss", "0002_remove_org_industry_remove_org_roles_role_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="org",
            name="industry1",
        ),
        migrations.AddField(
            model_name="org",
            name="industry",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="industry",
                to="industry.industry",
            ),
        ),
        migrations.AlterField(
            model_name="org_roles",
            name="org",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="org",
                to="orgss.org",
            ),
        ),
        migrations.AlterField(
            model_name="weightage",
            name="competency",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rolecompetency",
                to="competency.competency",
            ),
        ),
    ]
