# Generated by Django 4.2.4 on 2023-10-04 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgss', '0002_weightage_role_competency_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weightage',
            old_name='role_competency',
            new_name='competency',
        ),
        migrations.RenameField(
            model_name='weightage',
            old_name='weight',
            new_name='weightage',
        ),
        migrations.RemoveField(
            model_name='weightage',
            name='subcompetency',
        ),
    ]
