# Generated by Django 4.2.4 on 2023-10-11 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competency', '0009_competency1_master_competency'),
        ('orgss', '0003_rename_role_competency_weightage_competency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weightage',
            name='competency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rolecompetency1', to='competency.competency1'),
        ),
    ]
