# Generated by Django 4.2.4 on 2024-02-22 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("industry", "0002_rename_industry_description_industry_description_and_more"),
        ("quiz", "0002_remove_quiz_roles_quiz_org_role"),
        ("accounts", "0010_remove_account_role"),
        ("sean", "0008_remove_item_role"),
        ("orgss", "0003_remove_org_industry1_org_industry_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubOrg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                (
                    "description",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="weightage",
            name="org_role",
        ),
        migrations.AlterField(
            model_name="org",
            name="industry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="industry",
                to="industry.industry",
            ),
        ),
        migrations.DeleteModel(
            name="Org_Roles",
        ),
        migrations.AddField(
            model_name="suborg",
            name="org",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="org",
                to="orgss.org",
            ),
        ),
        migrations.AddField(
            model_name="weightage",
            name="suborg",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="suborg",
                to="orgss.suborg",
            ),
        ),
    ]
