# Generated by Django 4.2.4 on 2024-02-23 04:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orgss", "0005_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="org",
            name="name",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
