# Generated by Django 4.2.4 on 2023-09-27 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orgss', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_text', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=500)),
                ('option1_weight', models.IntegerField(default=1)),
                ('option2_weight', models.IntegerField(default=1)),
                ('option3_weight', models.IntegerField(default=1)),
                ('answer_count', models.IntegerField(default=1)),
                ('answer', models.CharField(choices=[('Opt1', 'Option 1'), ('Opt2', 'Option 2'), ('Opt3', 'Option 3')], default='Opt1', max_length=4)),
                ('feedback1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fdb1', to='quiz.feedback')),
                ('feedback2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fdb2', to='quiz.feedback')),
                ('feedback3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fdb3', to='quiz.feedback')),
                ('option1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opt1', to='quiz.option')),
                ('option2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opt2', to='quiz.option')),
                ('option3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opt3', to='quiz.option')),
            ],
        ),
        migrations.CreateModel(
            name='YourAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz_Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_orgname', models.CharField(max_length=500)),
                ('quiz_org_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org4', to='orgss.org')),
                ('quiz_org_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role4', to='orgss.org_roles')),
                ('quizquestion_name', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='quiz.quiz')),
            ],
        ),
    ]
