# Generated by Django 4.2.4 on 2024-02-22 17:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quiz_roles",
            name="quiz_org_role",
        ),
    ]
