# Generated by Django 4.2.4 on 2023-09-27 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PowerWords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(default=1)),
                ('sentence', models.CharField(default='sentence', max_length=250)),
                ('power_word_name', models.CharField(default='pw', max_length=250)),
                ('word', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='words.words')),
            ],
        ),
        migrations.CreateModel(
            name='NegativeWords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(default=-7)),
                ('sentence', models.CharField(default='sentence', max_length=250)),
                ('negative_word_name', models.CharField(default='ww', max_length=250)),
                ('word', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='words.words')),
            ],
        ),
        migrations.CreateModel(
            name='EmotionWords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emotion_word_name', models.CharField(max_length=250)),
                ('word', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='words.words')),
            ],
        ),
    ]
