# Generated by Django 4.2.6 on 2023-10-19 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0002_powerwords_negativewords_emotionwords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emotionwords',
            name='word',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='eww', to='words.words'),
        ),
        migrations.AlterField(
            model_name='negativewords',
            name='word',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='nww', to='words.words'),
        ),
        migrations.AlterField(
            model_name='powerwords',
            name='word',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pww', to='words.words'),
        ),
    ]
