# Generated by Django 4.2.4 on 2023-10-04 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competency', '0006_competency1'),
        ('words', '0003_rename_negativewords_negativewords1_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NegativeWords1',
            new_name='NegativeWords',
        ),
        migrations.RenameModel(
            old_name='PowerWords1',
            new_name='PowerWords',
        ),
    ]
