# Generated by Django 4.2.4 on 2024-02-28 17:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_account_org"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
