# Generated by Django 4.2.4 on 2023-08-31 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0001_initial'),
        ('organisation', '0002_org_roles'),
        ('accounts', '0002_account_is_email_confirmed_userprofile_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='user_org',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='userorg1', to='organisation.org'),
        ),
        migrations.AddField(
            model_name='account',
            name='user_role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='roles2', to='role.roles'),
        ),
        migrations.AddField(
            model_name='account',
            name='user_subrole',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='roles3', to='role.sub_role'),
        ),
    ]
