# Generated by Django 4.2.4 on 2023-10-01 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='scenarios_attempted_score',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
