# Generated by Django 4.2.4 on 2023-10-01 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_scenarios_attempted_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='scenarios_attempted_score',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
