# Generated by Django 4.2.4 on 2023-09-02 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_user_org_account_user_role_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='user_org',
        ),
        migrations.RemoveField(
            model_name='account',
            name='user_role',
        ),
        migrations.RemoveField(
            model_name='account',
            name='user_subrole',
        ),
    ]
