# Generated by Django 4.2.6 on 2023-10-19 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgss', '0002_remove_org_industry_remove_org_roles_role_and_more'),
        ('accounts', '0003_remove_account_role_userprofile_pw_competency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orgss.org_roles'),
        ),
    ]
