# Generated by Django 4.2.6 on 2023-10-19 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgss', '0002_remove_org_industry_remove_org_roles_role_and_more'),
        ('accounts', '0004_account_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='orgss.org_roles'),
        ),
    ]
