# Generated by Django 4.2.4 on 2023-09-04 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0004_role_scenario_rolescenario_item'),
        ('accounts', '0005_account_user_org_account_user_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='userorg_roles',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='userorg1', to='organisation.org_roles'),
        ),
    ]
