# Generated by Django 4.2.6 on 2023-10-24 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_account_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='competency_score',
            field=models.TextField(blank=True, null=True),
        ),
    ]
