# Generated by Django 4.2.6 on 2023-10-24 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userprofile_competency_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user_scenario_bookmarked',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user_scenario_submitted',
        ),
    ]
