# Generated by Django 4.2.4 on 2023-09-04 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_account_userorg_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='user_org',
        ),
        migrations.RemoveField(
            model_name='account',
            name='user_role',
        ),
        migrations.RemoveField(
            model_name='account',
            name='user_subrole',
        ),
    ]
