# Generated by Django 4.2.4 on 2023-11-23 09:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_remove_userprofile_user_scenario_bookmarked_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="user_powerwords",
            field=models.TextField(default="upw"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="user_weakwords",
            field=models.TextField(default="uww"),
        ),
    ]
