# Generated by Django 4.2.4 on 2023-09-06 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_account_user_org_remove_account_user_role_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='userorg_roles',
            new_name='role',
        ),
    ]
