# Generated by Django 4.2.4 on 2023-09-12 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_rename_userorg_roles_account_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_scenario',
            field=models.CharField(default='', max_length=250),
        ),
    ]
