# Generated by Django 4.2.4 on 2024-02-22 17:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0009_alter_userprofile_scenario_attempt_pw_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="role",
        ),
    ]
