# Generated by Django 4.2.4 on 2024-02-23 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("orgss", "0005_role"),
        ("accounts", "0010_remove_account_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="orgss.role",
            ),
        ),
    ]
