# Generated by Django 4.2.4 on 2023-09-20 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0005_delete_role_scenario'),
        ('accounts', '0011_remove_account_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='role',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='organisation.org_roles'),
        ),
    ]
