# Generated by Django 4.2.4 on 2023-10-06 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_account_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='user_role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('user', 'User')], default='user', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='scenarios_attempted_score',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
