# Generated by Django 4.2.4 on 2023-10-13 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgss', '0004_alter_weightage_competency'),
        ('accounts', '0017_rename_jadu_asked_userprofile_scenarios_asked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='orgss.org_roles'),
        ),
    ]
