# Generated by Django 4.2.4 on 2023-09-04 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competency_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Sub_Competency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcompetency_name', models.CharField(max_length=250)),
                ('sub_competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role', to='competency.competency')),
            ],
        ),
    ]
