# Generated by Django 4.2.4 on 2023-10-19 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competency', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competency',
            name='competency_sentiment',
            field=models.ManyToManyField(blank=True, to='competency.senti'),
        ),
    ]
