# Generated by Django 4.2.4 on 2023-09-20 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competency', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sub_competency',
            name='sub_competency',
        ),
        migrations.AddField(
            model_name='competency',
            name='sub_competency',
            field=models.ManyToManyField(blank=True, limit_choices_to={'subcompetency_name': True}, to='competency.sub_competency'),
        ),
    ]
