# Generated by Django 4.2.4 on 2023-09-27 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0002_powerwords_negativewords_emotionwords'),
        ('competency', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub_competency',
            name='emotion_words',
            field=models.ManyToManyField(blank=True, to='words.emotionwords'),
        ),
        migrations.AddField(
            model_name='sub_competency',
            name='negative_words',
            field=models.ManyToManyField(blank=True, to='words.negativewords'),
        ),
        migrations.AddField(
            model_name='sub_competency',
            name='power_words',
            field=models.ManyToManyField(blank=True, to='words.powerwords'),
        ),
    ]
