# Generated by Django 4.2.4 on 2023-09-26 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competency', '0003_alter_competency_sub_competency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competency',
            name='competency_name',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_competency',
            name='subcompetency_name',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
