# Generated by Django 4.2.4 on 2023-10-04 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0002_powerwords_negativewords_emotionwords'),
        ('competency', '0004_alter_competency_competency_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sub_Competency1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('emotion_words', models.ManyToManyField(blank=True, to='words.emotionwords')),
                ('negative_words', models.ManyToManyField(blank=True, to='words.negativewords')),
                ('power_words', models.ManyToManyField(blank=True, to='words.powerwords')),
            ],
        ),
    ]
