# Generated by Django 4.2.4 on 2023-10-04 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competency', '0005_sub_competency1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competency1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competency_name', models.CharField(max_length=250, unique=True)),
                ('sub_competency', models.ManyToManyField(blank=True, to='competency.sub_competency1')),
            ],
        ),
    ]
