# Generated by Django 4.2.4 on 2023-10-05 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competency', '0006_competency1'),
    ]

    operations = [
        migrations.CreateModel(
            name='senti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='competency1',
            name='competency_sentiment',
            field=models.ManyToManyField(blank=True, to='competency.senti'),
        ),
    ]
