# Generated by Django 4.2.4 on 2023-10-09 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competency', '0007_senti_competency1_competency_sentiment'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterCompetency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
            ],
        ),
    ]
