# Generated by Django 4.2.4 on 2023-10-11 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competency', '0008_mastercompetency'),
    ]

    operations = [
        migrations.AddField(
            model_name='competency1',
            name='master_competency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='competency.mastercompetency'),
        ),
    ]
