# Generated by Django 4.2.4 on 2023-10-11 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competency', '0009_competency1_master_competency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competency',
            name='sub_competency',
        ),
    ]
