# Generated by Django 4.2.4 on 2023-10-11 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competency', '0010_remove_competency_sub_competency'),
        ('sean', '0059_alter_emotionwords_competencys_and_more'),
        ('organisation', '0008_alter_org_roles_role_competency_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Competency',
        ),
    ]
