# Generated by Django 4.2.4 on 2023-10-11 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sean', '0060_alter_emotionwords_sub_competency_and_more'),
        ('competency', '0011_delete_competency'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sub_Competency',
        ),
    ]
