# Generated by Django 4.2.6 on 2023-10-11 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competency', '0012_delete_sub_competency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competency1',
            name='master_competency',
        ),
        migrations.AddField(
            model_name='mastercompetency',
            name='master_competency',
            field=models.ManyToManyField(blank=True, to='competency.competency1'),
        ),
    ]
