# Generated by Django 4.2.4 on 2023-12-05 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IndividualInputScenarios",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("going_for", models.CharField(blank=True, max_length=200, null=True)),
                ("with_who", models.CharField(blank=True, max_length=200, null=True)),
                ("help_on", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "come_across_as",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "not_come_across_as",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Individual Input Scenarios",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="IceBreaker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("going_for", models.CharField(blank=True, max_length=200, null=True)),
                ("with_who", models.CharField(blank=True, max_length=200, null=True)),
                ("help_on", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "come_across_as",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "not_come_across_as",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "IceBreakers",
                "ordering": ["-created_at"],
            },
        ),
    ]
