# Generated by Django 4.2.4 on 2023-12-23 06:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("icebreaker", "0002_alter_icebreaker_created_by_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="individualinputscenarios",
            old_name="going_for",
            new_name="need_help_on",
        ),
        migrations.RenameField(
            model_name="individualinputscenarios",
            old_name="help_on",
            new_name="need_to_talk",
        ),
        migrations.RenameField(
            model_name="individualinputscenarios",
            old_name="with_who",
            new_name="want_to_say",
        ),
    ]
