# Generated by Django 4.2.4 on 2023-08-31 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Sub_Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subrole_name', models.CharField(max_length=250)),
                ('sub_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role', to='role.roles')),
            ],
        ),
    ]
