# Generated by Django 4.2.4 on 2023-09-24 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0007_rename_org_industry_org_industry_and_more'),
        ('role', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Roles',
            new_name='Role',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='role_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='sub_role',
            old_name='sub_role',
            new_name='role',
        ),
        migrations.RenameField(
            model_name='sub_role',
            old_name='subrole_name',
            new_name='subrole',
        ),
    ]
