# Generated by Django 5.0.2 on 2024-03-23 14:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("SaaS", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feature",
            name="frequency",
            field=models.CharField(
                choices=[
                    ("unlimited", "Unlimited"),
                    ("annual", "Annual"),
                    ("monthly", "Monthly"),
                    ("weekly", "Weekly"),
                ],
                default="unlimited",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="featurelist",
            name="frequency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("unlimited", "Unlimited"),
                    ("day", "Day"),
                    ("week", "Week"),
                    ("month", "month"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
