# Generated by Django 5.0.2 on 2024-03-23 17:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("SaaS", "0002_alter_feature_frequency_alter_featurelist_frequency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="saas",
            name="enddate",
            field=models.DateField(blank=True, null=True),
        ),
    ]
