# Generated by Django 4.2.4 on 2023-11-29 15:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("freemium", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="freemium",
            name="access_time",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="start_date",
        ),
        migrations.AddField(
            model_name="subscription",
            name="end_date_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subscription",
            name="start_date_time",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
