# Generated by Django 5.0.2 on 2024-03-20 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("series", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SeasonLota",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=300)),
                (
                    "image",
                    models.FileField(
                        blank=True, null=True, upload_to="media/seasons/lota"
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="series.seasons"
                    ),
                ),
            ],
        ),
    ]
