# Generated by Django 5.0.2 on 2024-03-25 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assessments", "0004_assessment_is_approved_assessment_is_live"),
        ("series", "0002_seasonlota"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assessmentseason",
            name="assessment",
        ),
        migrations.AddField(
            model_name="assessmentseason",
            name="assessments",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="assessments.assessment",
            ),
        ),
    ]
