# Generated by Django 5.0.2 on 2024-04-17 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("QuadGame", "0002_alter_quadgameresult_unique_together"),
        ("series", "0003_remove_assessmentseason_assessment_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuadGameSeason",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quadgame",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="QuadGame.quadgame",
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="series.seasons"
                    ),
                ),
            ],
        ),
    ]
