# Generated by Django 5.0.2 on 2024-04-21 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("SnakeLadderGame", "0001_initial"),
        ("series", "0004_quadgameseason"),
    ]

    operations = [
        migrations.CreateModel(
            name="SnakeLadderGameSeason",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="series.seasons"
                    ),
                ),
                (
                    "snakeladdergame",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="SnakeLadderGame.snakeladdergame",
                    ),
                ),
            ],
        ),
    ]
