# Generated by Django 4.2.4 on 2024-01-07 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("competency", "0003_rename_name_competency_competency_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Interest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("interest", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="SeanScenarios",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scenario", models.CharField(max_length=1000)),
                ("scenario_answer", models.TextField(blank=True, null=True)),
                ("scenario_answer_count", models.IntegerField(default=0)),
                (
                    "thumbnail",
                    models.FileField(
                        blank=True, null=True, upload_to="media/scenarios/thumbnail"
                    ),
                ),
                ("level", models.IntegerField(default=0)),
                (
                    "competency",
                    models.ManyToManyField(blank=True, to="competency.competency"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Situations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("situation", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Tags",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="SeanScenariosTags",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sean_scenarios.seanscenarios",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sean_scenarios.tags",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SeanScenariosSituations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sean_scenarios.seanscenarios",
                    ),
                ),
                (
                    "situation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sean_scenarios.situations",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SeanScenariosInterests",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "interest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sean_scenarios.interest",
                    ),
                ),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sean_scenarios.seanscenarios",
                    ),
                ),
            ],
        ),
    ]
