# Generated by Django 5.0.2 on 2024-04-16 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("competency", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QuadGame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "thubmnail",
                    models.FileField(
                        blank=True, null=True, upload_to="quadgame/thumbnail/"
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("postive_marks", models.IntegerField(default=0)),
                ("negative_marks", models.IntegerField(default=0)),
                (
                    "competency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="competency.competency",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QuadGameResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.IntegerField(default=0)),
                ("created_at", models.DateField(auto_now_add=True)),
                (
                    "quadgame",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="QuadGame.quadgame",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Quadrant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "thubmnail",
                    models.FileField(
                        blank=True, null=True, upload_to="quadrant/thumbnail/"
                    ),
                ),
                (
                    "quadgame",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="QuadGame.quadgame",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Statements",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("statement", models.TextField()),
                (
                    "thumbnail",
                    models.FileField(
                        blank=True, null=True, upload_to="statements/thumbnail/"
                    ),
                ),
                (
                    "quadrant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="QuadGame.quadrant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Questions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField()),
                (
                    "thumbnail",
                    models.FileField(
                        blank=True, null=True, upload_to="questions/thumbnail/"
                    ),
                ),
                ("timer", models.IntegerField(default=0)),
                (
                    "quadgame",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="QuadGame.quadgame",
                    ),
                ),
                ("statements", models.ManyToManyField(to="QuadGame.statements")),
            ],
        ),
    ]
