# Generated by Django 5.0.2 on 2024-04-17 16:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("QuadGame", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="quadgameresult",
            unique_together={("quadgame", "user")},
        ),
    ]
